######################################################################
# Automatically generated by qmake (2.01a) czw. sty 23 14:36:29 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += /usr/include
LIBS += -lcurl
# Input
SOURCES += test-curl.cc
