#!/bin/bash

YOUTUBE_DL=yt-dlp
YOUTUBE_DL_ARGS="-x --audio-format mp3 --add-metadata"
JOBS=10
tempfile=$(mktemp)

[ $# -gt 0 ] || exit 0
url=$1

echo "getting ids for the playlist"
$YOUTUBE_DL --get-id ${url} | tee $tempfile

for id in $(cat $tempfile) ; do

    if [ -e "*${id}*" ] ; then
        echo "${id} already downloaded, skipping"
        sed -i -e "/${id}/d" ${tempfile}
    fi
done

parallel --bar -j $JOBS -a $tempfile $YOUTUBE_DL $YOUTUBE_DL_ARGS

rm $tempfile
