######################################################################
# Automatically generated by qmake (2.01a) pon. mar 17 13:03:53 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += metadata.cpp
